### PR TITLE
38c3 bottle drop label template Idee

### PR DESCRIPTION
**Pull request by krumelmonster**
I saw by [the post](https://chaos.social/@marudor/113328050061393231) from @marudor on mastodon that you're looking for labels so I played around a bit (I'm not a designer). Assumed they need to be black on white? Should I try making a trash sign in the same style?

What do you think?

38c3-bw

### CODE REVIEW

**Comment by djerun** [comment]
please don't usj the logo font for info text. its unreadable

**Comment by marudor** [comment]
As @djerun said. Please dont use the logo font for info.

**Comment by krumelmonster** [comment]
working on it...
38c3-WIP

**Comment by krumelmonster** [comment]
What do you think about these proposals? Should I add both color and b/w versions to the pr?
38c3_trashcan-WIP-color 38c3-WIP-color
38c3_trashcan-WIP 38c3-WIP

**Comment by marudor** [comment]
Yeah, please add color and black&white.
Also no need for trash cans - we no longer organize that.

**Pull request merged**
